services:
  db:
    image: "postgres:15"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    volumes:
      - ".:/app"
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
    ports:
      - "8000:8000"

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind
