"""Nutrient model: ondelete='system user UUID'

Revision ID: 757845ad060b
Revises: e81aa810da37
Create Date: 2025-08-22 12:08:00.089752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757845ad060b'
down_revision: Union[str, Sequence[str], None] = 'e81aa810da37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('nutrients_created_by_fkey'), 'nutrients', type_='foreignkey')
    op.create_foreign_key(None, 'nutrients', 'users', ['created_by'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nutrients', type_='foreignkey')
    op.create_foreign_key(op.f('nutrients_created_by_fkey'), 'nutrients', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
