"""initial

Revision ID: 9a0a94375bb6
Revises: 
Create Date: 2025-08-18 22:29:47.811837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0a94375bb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('FOOD', 'DISH', 'MEAL', name='food_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recipe', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.Enum('GRAM', 'MILLIGRAM', 'MICROGRAM', 'KILOGRAM', 'KILOCALORIE', 'LITER', 'MILLILITER', 'TEASPOON', 'TABLESPOON', 'CUP', 'OUNCE', 'FLUID_OUNCE', 'POUND', 'PIECE', 'SLICE', 'SERVING', 'INTERNATIONAL_UNIT', name='unit_enum'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_nutrients',
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('nutrient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], ),
    sa.PrimaryKeyConstraint('food_id', 'nutrient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_nutrients')
    op.drop_table('users')
    op.drop_table('nutrients')
    op.drop_table('food')
    # ### end Alembic commands ###
