"""added created_by FK

Revision ID: a125908d410a
Revises: 6a7001a9afa6
Create Date: 2025-08-20 22:49:14.854711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a125908d410a'
down_revision: Union[str, Sequence[str], None] = '6a7001a9afa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('created_by', sa.UUID(), nullable=False, server_default="39391cb5-f563-427d-89d6-1cdd34e27f46"))
    op.create_foreign_key(None, 'food', 'users', ['created_by'], ['id'])
    op.add_column('nutrients', sa.Column('created_by', sa.UUID(), nullable=False, server_default="39391cb5-f563-427d-89d6-1cdd34e27f46"))
    op.create_foreign_key(None, 'nutrients', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nutrients', type_='foreignkey')
    op.drop_column('nutrients', 'created_by')
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_column('food', 'created_by')
    # ### end Alembic commands ###
