"""Food model: ondelete='system user UUID'

Revision ID: e81aa810da37
Revises: a294f321da11
Create Date: 2025-08-22 12:04:02.942845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81aa810da37'
down_revision: Union[str, Sequence[str], None] = 'a294f321da11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('food_created_by_fkey'), 'food', type_='foreignkey')
    op.create_foreign_key(None, 'food', 'users', ['created_by'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.create_foreign_key(op.f('food_created_by_fkey'), 'food', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
